spring:
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: create


    datasource:
        url: jdbc:mysql://localhost:3306/cinema
        username: user
        password: password
        driver-class-name: com.mysql.jdbc.Driver
server:
    port : 8080